language: python
python:
  - "3.5"
before_install:
  - pip install flake8
# command to install dependencies
install: "pip install -r requirements.txt"
# command to determine branches
branches:
  only:
    - master
# command to run tests
script:
  - flake8
  - python -m unittest discover -s test -p "*_exists.py"

after_success:
  - codecov
